version: '3.6'
services:
    salt3:
        build: './centos-apache-php'
        image: salt3
        ports:
        - ${FRONT_END_PORT}:80
        - ${BACK_END_PORT}:8080
        volumes:
        - ${SOURCE_PATH}:/opt/www/salt3
        - ./apache/vhost.conf:/opt/docker/etc/httpd/vhost.conf
        environment:
        - PHP_MEMORY_LIMIT=128M
