version: '3.6'
services:
    salt3:
        build: './centos-apache-php'
        image: salt3
        links:
        - mysql56
        ports:
        - ${APP_PORT}:80
        - 3000:3000
        - 8000:8000
        volumes:
        - ${SOURCE_PATH}:/opt/www/salt3
        - ./apache/vhost.conf:/opt/docker/etc/httpd/vhost.conf
        environment:
        - DB_HOST=mysql56
        - PHP_MEMORY_LIMIT=128M
    
    mysql56:
        image: mysql:5.6
        ports:
        - ${MYSQL_PORT}:3306
        volumes:
        - ${MYSQL_DATA}:/var/lib/mysql
        environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=123456 # mật khẩu root user