version: '3.6'
services:
    salt3:
        build: './centos-apache-php'
        image: salt3
        ports:
        - ${APP_PORT}:80
        - 3000:3000
        - 8000:8000
        volumes:
        - ${SOURCE_PATH}:/opt/www/salt3
        - ./apache/vhost.conf:/opt/docker/etc/httpd/vhost.conf
        environment:
        - PHP_MEMORY_LIMIT=128M
